[app]
title = StandXenon
package.name = standxenon
package.domain = org.standxenon
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf,json,mp3,wav
version = 1.1
requirements = python3,kivy==2.2.1,requests==2.31.0,supabase-py==0.4.2,plyer
orientation = landscape
osx.python_version = 3
osx.kivy_version = 2.2.0
fullscreen = 1
android.minapi = 21
android.ndk = 23b
android.sdk = 30
android.allow_backup = True
android.permissions = INTERNET,ACCESS_NETWORK_STATE
android.api = 30
android.gradle_dependencies = 
android.enable_androidx = True
android.keystore = 
android.keystore_alias = 
android.keystore_password = 
android.keystore_filenames = 
android.ndk_path = 
android.sdk_path = 
android.ant_path = 
android.bootstrapper = sdl2
android.applibs_shared = 
android.applibs_static = 
android.add_src = 
android.add_assets = 
android.add_res = 
android.add_libs_armeabi_v7a = 
android.add_libs_arm64_v8a = 
android.add_libs_x86 = 
android.add_libs_x86_64 = 
android.java_class_name = 
android.gradle_repository = 
android.gradle_dependencies = 
android.debug_mode = 0
android.release_mode = 0
android.accept_sdk_license = True
android.google_play_services = False
android.gms_version = 0
android.google_play_services_dependencies = 
android.google_play_services_required = False
android.google_play_services_enabled = False
android.gradle_plugin_google_services = False
android.lint = False
android.ignore_manifest = False
android.ignore_assets = False
android.ignore_python = False
android.ignore_java = False
android.ignore_so = False
android.ignore_apk = False
android.ignore_gradle = False
android.ndk = 23b
android.sdk = 30
android.ndk_path = 
android.sdk_path = 
android.ant_path = 
android.bootstrap = sdl2
android.enable_androidx = True
